apiVersion: apps/v1
kind: Deployment
metadata:
  name: octopus-relayer-barnacle
spec:
  selector:
    matchLabels:
      app: relayer
  template:
    metadata:
      labels:
        app: relayer
    spec:
      containers:
      - name: relayer
        image: "gcr.io/octopus-dev-309403/octopus-relayer:latest"
        env:
        - name: APPCHAIN_ID
          value: "barnacle"
        - name: RELAYER_PRIVATE_KEY
          value: "ed25519:2xUVVWxJamN17xYCP5Ev4oyhJ8MK6JN6xY3nS5vmdPHiAjoR5gjsk67R12EQTauphv21UYEvzDG8p19SHmSc33wX"
        - name: APPCHAIN_ENDPOINT
          value: "wss://barnacle.rpc.testnet.oct.network:9944"
        - name: NEAR_NODE_URL
          value: "https://rpc.testnet.near.org"
        - name: NEAR_WALLET_URL
          value: "https://wallet.testnet.near.org"
        - name: NEAR_HELPER_URL
          value: "https://helper.testnet.near.org"
